### ISSUE TITLE
Installer incorrectly compares Python modules with paths

### ISSUE THREAD

**Issue by mback2k** [jhemp/intelmq-tools#2]
In the following function incorrectly Python modules are compared with paths:

```
    def __get_bot_details(self, module: str) -> Optional[IntelMQBot]:
        bots = self.get_all_bots()
        for bot in bots:
            if bot.module == module:
                return bot
        return None
```

Instead at least this code should most likely look like this, because the `module` variable holds paths instead of module names:
```
    def __get_bot_details(self, module: str) -> Optional[IntelMQBot]:
        bots = self.get_all_bots()
        for bot in bots:
            if bot.file_path == module:
                return bot
        return None
```
with the condition changed to `if bot.file_path == module:`

**Comment by jhemp** [comment]
I agree this was messy as I did not fully understand the internal workings of intelmq, due to the support of intelmq 3.x this will now not happen anymore.
